---
- name: DNS Zone, Network, and Host Reservation
  hosts: localhost
  connection: local
  gather_facts: no   # running against local host

  vars:
          domain: campuswest.local
          dcomment: local DNS zone
          state: present
          networktocreate: 192.168.200.0/24
          netcomment: this is my second IPv4 network
          reservationreason: ansibledev education
          iptoreserve: 192.168.200.32

  vars_files:
          - vars/infoblox.creds   # contains nios_provider

  tasks:
          - name: "Create a forward DNS zone called {{ domain }}"
            nios_zone:
              name: "{{ domain }}"
              comment: "{{ dcomment }}"
              state: "{{ state }}"
              provider: "{{ nios_provider }}"    # credentials
  
          - name: Attempting to create a network on the default network view
            nios_network:
                    network: "{{ networktocreate }}"
                    comment: "{{ netcomment }}"
                    options:
                            - name: domain-name
                              value: "{{ domain }}"
                    state: "{{ state }}"
                    provider: "{{ nios_provider }}"
                    
          - name: Attempting an IPv4 reservation
            community.general.nios_fixed_address:
              name: ipv4_fixed
              ipaddr: "{{ iptoreserve }}"
              mac: 00:00:00:00:00:00
              network: "{{ networktocreate }}"
              network_view: default
              comment: "this port is reserved for {{ reservationreason }}"
              state: "{{ state }}"
              provider: "{{ nios_provider }}"