---
- name: Network Playbook to gather facts
  hosts: arista
  gather_facts: no
  connection: network_cli

  # these vars can be mapped other places
  # but need to be mapped for ansible to
  # connect to Arista switches
  vars:
    ansible_network_os: eos   # this must match a value on https://docs.ansible.com/ansible/2.9/network/user_guide/platform_index.html#settings-by-platform
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: admin       # un of switch
    ansible_ssh_pass: alta3   # pass of switch

  tasks:
  - name: Gather EOS facts   # all netmod (v2.9) https://docs.ansible.com/ansible/2.9/modules/list_of_network_modules.html
    eos_facts:
      gather_subset: all

  - name: what sort of facts did we get?
    debug:
            var: ansible_facts
